# ===============================
# Datasource Configuration
# ===============================
app.datasource.driver=${DB_DRIVER}
app.datasource.url=${DB_URL}
app.datasource.username=${DB_USERNAME}
app.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / Hibernate Configuration
# ===============================
app.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO}
app.jpa.hibernate.dialect=${HIBERNATE_DIALECT}
app.jpa.show-sql=${HIBERNATE_SHOW_SQL}